// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6JQUushU3hZfHXZKS2jQ4t39zKz9wQkA',
    appId: '1:959724000751:web:d0ad16a4b4243c480e921a',
    messagingSenderId: '959724000751',
    projectId: 'runtrack-80427',
    authDomain: 'runtrack-80427.firebaseapp.com',
    storageBucket: 'runtrack-80427.firebasestorage.app',
    measurementId: 'G-L0P6QKBH25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEpJs-OECYeiVA6dfONjYKqwQB6TDnOE4',
    appId: '1:959724000751:android:e1aeb574237654250e921a',
    messagingSenderId: '959724000751',
    projectId: 'runtrack-80427',
    storageBucket: 'runtrack-80427.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMN3w2GpBQKkStL5wbBir5hjYee3kVkOI',
    appId: '1:959724000751:ios:1f30013536d956050e921a',
    messagingSenderId: '959724000751',
    projectId: 'runtrack-80427',
    storageBucket: 'runtrack-80427.firebasestorage.app',
    iosBundleId: 'com.example.inzynierka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMN3w2GpBQKkStL5wbBir5hjYee3kVkOI',
    appId: '1:959724000751:ios:1f30013536d956050e921a',
    messagingSenderId: '959724000751',
    projectId: 'runtrack-80427',
    storageBucket: 'runtrack-80427.firebasestorage.app',
    iosBundleId: 'com.example.inzynierka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6JQUushU3hZfHXZKS2jQ4t39zKz9wQkA',
    appId: '1:959724000751:web:6a9b8837f0ffd4bc0e921a',
    messagingSenderId: '959724000751',
    projectId: 'runtrack-80427',
    authDomain: 'runtrack-80427.firebaseapp.com',
    storageBucket: 'runtrack-80427.firebasestorage.app',
    measurementId: 'G-TV0W7BLWE9',
  );
}
